<a href="https://colab.research.google.com/github/juancasi/data_science_fundamentals/blob/master/chapter_04/numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

In [3]:
import numpy as np

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [7]:
lista = np.array([7,8,4,5,1,2])
print(lista)

[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [7]:
print(lista[2:])

[4 5 1 2]


Using slicing print all the elements except the last one.



In [8]:
print(lista[:-1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [9]:
print(lista[1:(4+1)])  # Last index arrray position is exclusived for that reason is used (last_index + 1)

[8 4 5]


Reshape the array into a 3 rows and 2 cols (3,2).



In [14]:
newLista = np.reshape(lista,(3,2))
print(newLista)

[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [8]:
for i in range(len(lista)):
    print(lista[i])

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [11]:
lista2 = np.array([0,6,9])
print(lista2)


[0 6 9]


Join the two arrays.



In [12]:
listaCompleta = np.concatenate((lista, lista2))
print(listaCompleta)

[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [44]:
for i in range(len(listaCompleta)):
    numeroImpar = listaCompleta[i]
    if numeroImpar%2 == 0:
        pass
    else:
        print(numeroImpar)

7
5
1
9


In [49]:
listaImpar = np.where(listaCompleta%2 != 0)
print(listaCompleta[listaImpar])

[7 5 1 9]


Sort the joined array elements.



In [46]:
listaOrdenada = np.sort(listaCompleta)
print(listaOrdenada)

[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [4]:
mes =['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio',
'Agosto','Septiembre','octubre','noviembre', 'Diciembre']
print(mes)

['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'octubre', 'noviembre', 'Diciembre']


Split the months array in 4 periods of 3 elements each one.



In [5]:
periodo = np.reshape(mes,(4,3))
print(periodo)

[['Enero' 'Febrero' 'Marzo']
 ['Abril' 'Mayo' 'Junio']
 ['Julio' 'Agosto' 'Septiembre']
 ['octubre' 'noviembre' 'Diciembre']]


Create an array with genre information ['F','M','F','F','M','F'].



In [59]:
genero = ['F','M','F','F','M','F']
print(genero)

('F', 'M', 'F', 'F', 'M', 'F')


Find the indexes where the value is F.



In [81]:
for i in range(len(genero)):
    valorF = genero[i]
    if valorF == 'F':
        print(i)
    else:
        pass

0
2
3
5


Store in an array the age information [18,20,19,23,19,20].



In [82]:
edad =[18,20,19,23,19,20]
print(edad)

[18, 20, 19, 23, 19, 20]


Create a filter array with values < 20.



In [96]:
filtro = []
for i in edad:
  if i < 20:
    filtro.append(i)
print(filtro)

[18, 19, 19]


Change the 3 index element with a value of 22



In [97]:
edad[3] = 22
print(edad)

[18, 20, 19, 22, 19, 20]


Print the 4 index element.

In [98]:
print(edad[4])

19
